language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: JpxmvZ584JNpx4bzG78iRGZpnIUhjKfYU55Lr4RaWaBnxfC2/8fNIfXtXAZ8ihGX1iHOHbUXU7muo9LlJZEp+y+POdvVhHho4fhngR1DSvtH7Ddw4urho1nTSqu71nPsK2XYLOD9rK5Y+PzsyyoxdioZ2K3uoAnsEhwctl/O7ccQdKECjZ4CjsH1ZOrT2S58iBg5ZlDP5djHulonSkJ7VMwW4jEAf6U56NNKF2id7yXOa1scw9u/QWOmK/wTzI9zBAFbXEHiLXbmCkdACCKK6SgFCV6LinztjmWjyHdRHPZIu20l0HMZqgvD61p9F2fK+tBojiEinVOG+UlQq4x6ENBy6hZISy8033iYn58N77LrKkOHaGin1GFPRIZoiRe85ZEB4x1MqWa7tsBw5XYAaLdUXro7Bis2OoTc3ELh10wgpWyOv8+Xscj3KGfPDbGJo+XEVI9+9ms0SE7f4cy4H09KUzT5l/hXcUVMfH2llfKsCHVeN/pkA3qzHG5VfxzSs8aRCVxRUUQQpPrSlaAGneUC4/awbBKPbRQAJrnEax8zW1TKuqZYB1jQvSVj1z5cj+DZ7Om60IqObZjZfX+rFHga3neWPHJNJ6Vqt42uh1w0rnqc0e40q0HbQ6WhiW7YkEYlk0AzHxLh23J/szqu4GSRoIptWpmdAL/tg0sf03s=
  app: line-football-bot
