language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: BOqphOon8f3y+nAZI742kRvxcgQiNBGFJM6wUeezgsUH5ZsPk0I6LpzsH7FKeGRlnsN7q43SRqVTmUCfgkQqrdZ0EgdL/fec159qHivoIdwdIRpIE8XDv9XWJPjnvsqoZuLA3uF9i8/AsFCblnhlUH/9Dk0aOE+eFW+Xbz4Bb2tBA+Yd9Q2OnCR0c44XYTZILz38SnGdHWbpt0AlNZIlgiBTwkDYBQre73IRA8MP7BFxdvggz7MJotgmqzTjCEaoP08MZ8YZZ9qA3IfTOmslywGY+HAdkq1s3EoDvf+be6s8D6c+uGZHusWOVxu8oYPJyJnT1xOe1fgiSC6gTF/qxZQHQ+TYfSp9uFZ8ws3KzRKRnwgYy9Y0sQbINSxFIEF/M6xoDNYPujRB4nsMELDMzsiNOhEYUI07xocCRwz8N8YglwNzNdVmn/Xe99jWmHm9ncft7Rc7BWmuY5CXTv1hEgb9A4EGf5xcCVBRTaMkzL3ke1Ofwjgfseleycok8oDtqq1u4YbiqZBv2kCfzOrmaFHYxIIUqmdCx1LmIN4A4NVFPBzCC8hGNQ9Lx6mxuh+TPFR8X0uCw78/jMPzE6yBbie0zOnqXBH2EYTIb3p1r5mkI1v1DRoThCQ2gQBrZktIkgJVFy4lmMo9XXBVY80o5yFgjz1fVKVk8GeVmaIyAac=
  app: line-football-bot
